### ISSUE TITLE
Crafttweaker scripts error 

### ISSUE THREAD

**Issue by ghost** [Ender-Development/Aetherworks-Extended-Life#4]
```
//fix aetherwork metalformer don't receive unidict bronze
MetalFormer.removeRecipesByOutput(<aetherworks:item_resource:4>);
MetalFormer.removeRecipesByOutput(<aetherworks:item_resource:3>);

MetalFormer.addRecipe(<thermalfoundation:material:163>, <liquid:aetherworks.aetherium_gas>*144, <aetherworks:item_resource:4>,2100);
MetalFormer.addRecipe(<thermalfoundation:material:355>,<liquid:aetherworks.aetherium_gas>*144, <aetherworks:item_resource:3>,2100);

```
```
[INITIALIZATION][CLIENT][FATAL] [crafttweaker]: Error executing {[0:crafttweaker|reloadable]: recipes\mods\Ember.zs}: net.minecraft.item.ItemStack cannot be cast to net.minecraft.item.crafting.Ingredient
java.lang.ClassCastException: net.minecraft.item.ItemStack cannot be cast to net.minecraft.item.crafting.Ingredient
	at v0id.aw.compat.crafttweaker.MetalFormer.removeRecipesByOutput(MetalFormer.java:35)
	at recipes\mods\Ember.__script__(recipes\mods\Ember.zs:56)
	at __ZenMain__.run(recipes\mods\Ember)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:240)
	at crafttweaker.runtime.CrTTweaker.loadScript(CrTTweaker.java:105)
	at youyihj.zenutils.impl.runtime.ZenUtilsTweaker.loadScript(ZenUtilsTweaker.java:95)
	at crafttweaker.mc1120.events.CommonEventHandler.registerRecipes(CommonEventHandler.java:71)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2526_CommonEventHandler_registerRecipes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:636)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandlerMixin.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(MinecraftMixin.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(MinecraftMixin.java:6601)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:100)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```
PS: The crafting materials of aether ingot and aether gem do not seem to support the ore dictionary, and the corresponding items of embers are automatically disabled, so I use this script to fix it

**Comment by MasterEnderman** [comment]
The crafttweaker integration is so cursed. I probably broke more of it after adding support for GroovyScript.
I'll take a look at it later today. Thanks for the report.
